### ISSUE TITLE
Peer review 1

### ISSUE THREAD

**Issue by Caroline-Seip** [STAT545-UBC-students/hw01-shreeramsenthi#2]
Hey Sheeram!

I liked your edit of the README.md file. It was simple, well laid out and I liked the raccoons! One thing to pay attention to is that because you put a picture right after your sentence in the code it cut off your sentence. Just make sure you look at the final version next time.

Your R Markdown assignment started out great, with good descriptions. My only issue is that I couldn't see any of the code for your graphs in the .md file, so I don't know the code you used to create those graphs. The graphs look great but would love to see the code for how to do that. Not sure what it was that made the code not show up, but again just double check next time so that everything is showing how you want it to before submitting.

**Comment by shreeramsenthi** [comment]
Hey Caroline, thanks for the feedback. I purposefully suppressed the code since I thought it looked cluttered, but your right that it would be more useful to have it visible. I tried to take your advice for the second assignment.

Thanks again,
Shree
