### ISSUE TITLE
peer review

### ISSUE THREAD

**Issue by zuhengxu** [STAT545-UBC-students/hw01-shreeramsenthi#3]
Hi shreeram @shreeramsenthi !

I’ve just reviewed your hw01 and pretty enjoyed going through your repo! In this issue, I just wanted say something I like and maybe some places can be improved.
 
### `README.md`
It's really creative to choose those two pictures about your background, I was totally attracted by them. The header here is well organized and makes it easy to follow up this file. You've also used various markdown features, which is great!
 But I think it would be better to add words or coeds insert in your readme file.Maybe just get a bit more into it would improve the whole level of your homework.

### `Rmd`/`md`
It is definitely great to use your own dataset here and the plots here is fantastic, seems you are good at using `ggplot2`! 
If I have to say some suggestions, I am expecting some in-code annotations, which can help the codes more readable.

Generally speaking, you've done a good job! hope my comments can be helpful to you!

Based on the grading scheme, I will give you 400!

David

**Comment by shreeramsenthi** [comment]
Hey David, thanks for the feedback! I tried taking your advice on homework 2.
